language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
addons:
  postgresql: '9.6'
install:
  - bundle install
  - nvm install 8.11.2
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test
script:
  - bundle exec rails webpacker:compile
  - bundle exec rails spec
  - bundle exec govuk-lint-ruby app config db lib spec --format clang
deploy:
  provider: heroku
  api_key:
    secure: M7nBYOA/gnjz/4p4D6zkzKjeyEmaRo76oJ+3g5FHnUUFd3Kyf/RJNWhcl9vqEq3lzKueI1CdQtFkDZRVouYNY+vdv45nR6C9J6Tr1tWPJUaiFt2LI8Ta4mKexpCkbNlVuHxGiO+8TjXtYRajBBz2Bzvgcvje/XieKIN/QnuY0uTtLV3WicZlizAdA2yersOtzd0jq2sVY8UGlL0bHjF6C3PrG54bmFNgX/smJsWoCxTr1w9heuwkBUJMSZCtzwI3FrBTU+ZAs3sKCCI8KbKAL7p4sRZ6eWMD4oxF1D4rSe10/VRfW1OBVBMY0fmk/01EcFl5KKB1Y0wf3dOWhO0oMvOeDu3J57JPqNPKTk9WweE6Kmg5EGM0vnyzJNVn/gdsH2JOrfsUPYXxRAwypsMcXB+ldntWRK4/M37L+rNwYhFjRVk1wmL5id5wxGTLuOJGosTCjujSuOIyqbPk7TjAwUvJoAAsEBWw2lbhmovcBSmgo8kx2xhA1q3fBC0SBJKHX5sHg4okWb3sQgjGci+0QL4BAI1+RG9ZflzVrCY4vny7jF1RdNn+B3gkNJb/F5M6+70Y3xOIZELr2SfnrKl3CRN93CSBKIspmYFJJkadR607fNUkjrd/t9ZZpQMLE6lihCeMpIdQMMXxMpS11OcsYKB3bWEorrIEWlZbM1yBdIo=
  app: eduk-cms-spike
  on:
    repo: dankmitchell/eduk-cms-spike
